# Generated by Django 4.1.7 on 2023-06-06 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0002_subscription_expire_at_subscription_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_id",
        ),
    ]
