# Generated by Django 4.1.7 on 2023-06-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_delete_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrict",
            name="post",
            field=models.IntegerField(),
        ),
    ]
