# Generated by Django 4.1.7 on 2023-06-08 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0006_remove_restrict_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
