# Generated by Django 4.1.7 on 2023-06-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0007_alter_plan_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
