# Generated by Django 4.1.7 on 2023-06-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0008_alter_plan_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrict",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="membership.plan",
            ),
        ),
    ]
