# Generated by Django 4.0.5 on 2023-06-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedtopic',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.DeleteModel(
            name='RelatedTopic',
        ),
    ]
