# Generated by Django 4.1.7 on 2023-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="tags11",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
