# Generated by Django 4.1.7 on 2023-06-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_remove_relatedtopic_tags_delete_testing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="is_paid",
            field=models.BooleanField(
                default=False,
                verbose_name="Meter my story it is eligible to your when you publish",
            ),
        ),
    ]
