# Generated by Django 4.1.7 on 2023-05-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_remove_posts_tags11_remove_posts_tags_posts_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="tags",
        ),
        migrations.AddField(
            model_name="posts",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="post.tag"),
        ),
    ]
