# Generated by Django 4.1.7 on 2023-06-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_posts_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
