# Generated by Django 4.1.7 on 2023-06-09 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_remove_posts_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookmark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
