# Generated by Django 4.1.7 on 2023-06-12 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0007_createbookmarklist_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posts",
            options={},
        ),
    ]
