# Generated by Django 4.0.5 on 2023-06-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow1',
        ),
    ]
