# Generated by Django 4.1.7 on 2023-06-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0006_remove_restrict_created_at_and_more"),
        ("user", "0002_delete_follow1"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.plan",
            ),
        ),
    ]
