# Generated by Django 4.1.7 on 2023-06-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0007_alter_plan_user"),
        ("user", "0003_profile_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_plan",
                to="membership.plan",
            ),
        ),
    ]
