# Generated by Django 4.1.7 on 2023-06-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0008_alter_plan_user"),
        ("user", "0005_alter_user_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="membership.plan",
            ),
        ),
    ]
