# Generated by Django 4.1.7 on 2023-06-09 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_user_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
